lib/network_utils.ml

In 3.12+ kernels, this key also exists for OVS ports.
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

CA-151464: Don't assume interface is bonded if master sysfs key exists

---

networkd/network_monitor_thread.ml

The login_with_password XenAPI call takes an "originator"
string as its fourth parameter.
If a client does this, then it gets its own pool of xapi sessions.
Moreover it will not have its xapi sessions destroyed prematurely
as a result of some other misbehaving client that keeps creating
sessions and not logging out of them.
This patch adds the "originator" to all invokes of
login_with_password.
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>

CP-9895: Added originator for xapi login_with_password

---

lib/network_utils.ml

Use a switch `--xapi` to call fcoe driver

---

lib/network_utils.ml
networkd/network_server.ml

dhclient handles all ipv6 related configurations and hence dhcp6
is not required
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>

CP-15312: Remove dhcp6 exception from toolstack startup

---

networkd/network_server.ml

A recent change[1] to support clearing of DNS entries when using Static
mode networking has caused DNS entries to be cleared when using DHCP.
We need to support the following cases:
1. DHCP;
2. Static with non-empty DNS; and
3. Static with empty DNS.
We currently don't support DHCP with a DNS override so we don't need to
consider this in this patch.
This patch changes the order of setting the DNS for the host and calling
dhclient so that the above three use-cases are honoured.
[1]: d49bc77 CA-198824: Allow empty DNS when configuring static IP
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

CA-199405: Set DNS before making DHCP request

---

networkd/network_server.ml

Commit 1a2383c5 did not solve the original problem in case a DHCP config is
applied twice consecutively (for example when the PIF is replugged when xapi is
restarted). The second time round, the dhclient process is already running and
does not reapply the DNS servers after being cleared by the preceeding
`set_dns` call.
This is still not a great solution. The `dns` field should really be an option
type so that we don't have to derive the intention of the caller by looking at
other fields. Changing the type, however, would require us to implement some
upgrade logic first.

CA-199404: Only apply DNS settings in Static4 mode

---

.travis.yml

This will build and test xcp-networkd using the new xenserver-build-env
build scripts.

CP-15745: Add .travis.yml

---

lib/network_utils.ml

CA-210158: Only set mac-table-size on real (non-VLAN) bridges

---

lib/network_utils.ml
networkd/network_server.ml

Bond properties such as the bond mode were not updated if the bond already
existed. This caused XenAPI commands such as Bond.set_mode to have no immediate
effect (changes would be implemented only after re-plugging or rebooting).
Also make sure that bond-manipulation functions in Network_utils are idempotent,
as the high-level function call is supposed to be idempotent.

CA-210762: Linux bridge: Always update bond properties

---

lib/network_utils.ml

Some sysfs files are "empty", for a good reason.

CA-211448: When reading a line from sysfs, translate End_of_file to ""

---

networkd/network_monitor_thread.ml

We don't use the stats for these devices, so lets not spend time on them.
Furthermore, due to the fact that the Sysfs.read_one_line and therefore the
Sysfs.get_pci_ids function now log errors, and the loopback and bond devices
do not have PCI info in sysfs, this was causing lots of log spam.

Don't collect stats for loopback and bond devices

---

lib/network_utils.ml

The bond mode node in sysfs includes a number beside the
name of the mode. We should not consider this number while
comparing current-state with desired-state to re-apply the mode.

CA-211108: Don't consider the number beside the bond mode in sysfs

---

lib/network_utils.ml
networkd/network_server.ml

Function `is_vlan_in_use` will identify the VLAN which is
in use by FCoE and unknown to XAPI.
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>

CA-201728: Add new function `is_vlan_in_use`

---

lib/network_utils.ml
networkd/network_server.ml
networkd/networkd.ml
xcp-networkd.conf

From xcp-networkd.conf file we can configure enic-workaround-until-version="x.x.x.x"
to the version till enic driver workaround will be applied or
set the version to an empty string for not applying the workaround.

CA-219257: Make enic driver workaround configurable.

---

lib/network_utils.ml
networkd/network_server.ml

This adds some protection against unicast floods (which happen as part of MAC
learning) getting out of hand.

Set no-flood on PVS-proxy ports

---

networkd/network_monitor_thread.ml
networkd/networkd.ml

This way we have tighter control over what interfaces are monitored, which are
essentially just PIFs (eth*) and VIFs (vifx.y). Recently, we have had to extend
the blacklist several times, because devices with different names appeared,
which we do not want to monitor.

Change monitor blacklist into whitelist

---

networkd/network_server.ml

Call mod-port on parent bridge, not "fake" VLAN bridge

---

lib/network_utils.ml

OVSDB server can handle at most 10 connections at a time, to avoid issues we rate-limit the number of concurrent connections. The limit is lower than 10 because we need to take into account the possibility of calls from other scripts.
This will not compile until https://github.com/xapi-project/stdext/pull/17 is merged

CA-225272: rate-limit calls to `ovs-vsctl`

---

networkd/network_server.ml

This (relatively new) kind parameter was not passed on to the function that
adds the port to the bridge, so that it would add a port of the wrong kind.

CA-234506: Don't lose the port `kind` param in bridge.make_config

---

lib/network_utils.ml
networkd/network_server.ml

Redefine `Interface.set_ipv4_conf` to keep being idempotent but avoid flushing ip addresses on xapi restart if their ips are the expected ones.

CA-239919: Static IP briefly flushed when a Static IPv4 is set

---

lib/network_utils.ml
networkd/network_server.ml

This function will provide the physical interfaces underneath
the bridge.
Bridge can be on:
1) Physical interface.
2) VLAN on physical interface.
3) On a bond.
4) VLAN on a bond.

CA-223676: Add function `get_physical_interfaces` to networkd

---

networkd/network_server.ml

dhclient now sets limited address lifetimes on DHCP-allocated addresses:
7: xenbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1
link/ether 18:a9:9b:23:e8:af brd ff:ff:ff:ff:ff:ff
inet 10.71.152.106/21 brd 10.71.159.255 scope global dynamic xenbr0
valid_lft 16017sec preferred_lft 16017sec
If we switch from DHCP to static addressing using the same IP address,
xcp-networkd will see that the address is already assigned to the
interface and will not update it.   Without dhclient updating the lifetime
timer, the address will eventually time out and the kernel will remove it.
To avoid this problem, we now flush all an interface's addresses when
switching from DHCP to static addressing, then re-add the static address.
This results in the lifetime being set to …

CA-250444: Always flush addresses when switching from DHCP to static

---

lib/network_config.ml

Host installer doesn't write management_interface into inventory.
As firstboot needs to create management pif and update the inventory.
In case of management on vlan xcp-networkd must not create vlan bridge
if management_interface is empty.
Let the firstboot create the VLAN and set the management PIF.

CA-254379: Fixing vlan bridge create during host installation.

---

lib/network_config.ml

Removes spurious backtrace occurring on first boot
because config file /var/lib/xcp/networkd.db does
not exist yet.
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>

CP-22405: Log message for config file not existing

---

lib/network_utils.ml
networkd/network_server.ml

Signed-off-by: Liang Dai <liang.dai1@citrix.com>

CP-23093: Implement toggle of IGMP snooping on xcp-networkd

---

lib/network_utils.ml
networkd/networkd.ml

CP-23098 implemented a new OVS toggle `enable-ipv6-mcast-snooping` and set its default value to `true` for ensuring compatible with OVS.
This PR make the default value of this toggle to `false` because XenServer do not support IPv6 multicast snooping.

CP-23843: Disable IPv6 multicast snooping for OVS in XenServer

---

lib/network_utils.ml
networkd/networkd.ml

Disable flooding of unregistered multicast traffic by default in XenServer
Signed-off-by: Ming Lu <ming.lu@citrix.com>

CP-23835: Disable flooding of unregistered traffic

---

lib/network_utils.ml
networkd/network_server.ml

If `ip link set` is used OVS will keep changing it back to the minimum MTU if you attach 2 VLANs (created on a bond) with different MTUs to the same VM.

CA-196520: use `mtu_request` in OVS to set interface MTU

---

lib/network_utils.ml

Match Sys_error("Invalid argument") and omit the error log.
For other error case, record the exception info and backtrace.

CA-268679 XAPI loop report (Sys_error "Invalid argument")

---

lib/network_config.ml
networkd/network_server.ml

During the port to Astring the function `Xstringext.String.split` (that preserves empty splitted strings) has been replaced in most places by `Astring.String.cuts ~empty:false` (filtering the empty splitted strings). 
In most cases this was just an optimization. In two cases the difference in behaviour could create issues in some corner cases. This commit restores the old behavior for those.
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

network_config, network_server: restore semantics of split

---

lib/jbuild
lib/network_utils.ml
networkd/network_server.ml
networkd/networkd.ml

Since a lot of changed have been made, I raised a new PR and closed the old one. Mainly I changed to use Rresult for all error handle.
I suppose the current sriov_error defined in IDL is too complex.
Currently:
```
type sriov_error =
| Device_not_found
| Bus_out_of_range
| Not_enough_mmio_resources
| Unknown of string
```
But actually XAPI will *not* match different tags with different behaviors. So I changed it to just
```
type sriov_error =
| Msg of string
```
moved functions related to ip link to module ip.
Refined function `parent_device_of_vf`
- directly use 'devices.(0)'
- use result type instead of exception
Refined function `device_index_of_vf`
- use result type instead of exception
Add new Dracut module
Get max/num vfs from sysfs with two functions:
- Sysfs.sriov_numvfs
- …

Mainly I changed to use Rresult for all error handle.

---

test/jbuild

When you are using jbuilder workspaces the _build dir may not be a subdir of the
source root.
Tell jbuilder to copy the test files from the source dir to the build dir
instead of reading them from the source dir during testing.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>

jbuilder runtest: make it work when _build is not subdir of source root

---

lib/network_utils.ml
networkd/network_server.ml

Before using sysfs interface to config SR-IOV, the function should ensure all VFs are unbound from pciback driver.

CA-286029: Disabling SR-IOV is failed on sysfs NIC

---

lib/network_utils.ml
networkd/network_server.ml

In order to ensure the Networkd to be idempotent, configuring VF with no VLAN and rate have to reset vlan and rate, since the VF might have previous configuration. Refering to http://gittup.org/cgi-bin/man/man2html?ip-link+8, set VLAN and rate to 0 means to reset them

CA-286290: A no-vlan SRIOV VIF shouldn't have a VLAN tag

---

lib/jbuild
lib/jsonrpc_client.ml
lib/jsonrpc_client.mli
networkd/networkd.ml
test/test_jsonrpc_client.ml
xapi-networkd.opam

* CA-236855: VM.clean_shutdown task not completing on slave
According to the discussion (also recorded in the ticket), this change
will use the newly created read_timeout and write_timeout to process
input and output from outside. Some updates according to Nanjing peer review.
Modified test case to remove the cases that is not applied.
Signed-off-by: YarsinCitrix <yarsin.he@citrix.com>

CA-236855: VM.clean_shutdown task not completing on slave

---

networkd/network_server.ml

OVS.set_mtu is a new function (since ed2151f8), which requires a newer version
of the OVS that supports the mtu_request feature. If the installed OVS does not
have this feature, then the function will raise an exception. For compatibility
reasons, we now catch this exception and fall back to Ip.link_set_mtu.

CA-291495: Fall back to Ip.link_set_mtu if OVS.set_mtu fails

---

networkd/jbuild
networkd/network_monitor_thread.ml

For compatibility with new rpclib 5.8.0, see failure in https://github.com/xapi-project/xs-opam/pull/291 -
the Rpc_client module has been removed from ocaml-rpc

network_monitor_thread: use Xmlrpc_client instead of Rpc_client

---

.travis.yml

Travis was failing with 4.06, see https://travis-ci.org/xapi-project/xcp-networkd/builds/470123775?utm_source=github_status&utm_medium=notification

Use OCaml 4.07

---

lib/network_config.ml
lib/network_utils.ml
networkd/network_server.ml

On first boot networkd may create a vlan named xentemp and the firstboot script call xapi to create that same vlan to get recognized by xapi.
networkd need to recognise this case, otherwise an error occurs and the setup fails.

CA-310516: Detect vlan created on first boot as managed

---

lib/network_utils.ml
networkd/network_server.ml
networkd/networkd.ml

This reverts 9d5309e8018664ed2766e52aeeb1f39d26c5a88d. The reason is that the
workaround is once again needed on the current version of the enic driver.

CA-310413: Unconditionally apply enic workaround (again)

---

lib/network_utils.ml

PCI BDF format: up to 256 buses, each with up to 32 devices, each
supporting eight functions.
This commit fixes the regex match to include hex strings.

CA-320563: xcp-networkd: fix the regex match for PCI BDF string

---

lib/network_utils.ml

PCI BDF format: up to 256 buses, each with up to 32 devices, each
supporting eight functions.
This commit fixes the regex match to include hex strings.
Signed-off-by: Ming Lu <ming.lu@citrix.com>

CA-320563: re-submit for missing change on regex

---

lib/network_config.ml

DNS%d= is written by host-installer,
and DNS= would've been written by the non-hotfixed version of XAPI on
pool eject/network reset.
DNS1 could contain comma-separated values too, handle this by splitting each
value and then List.concat at the end.
See https://github.com/xapi-project/xen-api/pull/3931 why this is needed

CA-324959: suppport both DNS= and DNS%d= formats

---

lib/network_config.ml

This results in an empty /etc/resolv.conf when using static IPs:
```
systemctl stop xcp-networkd
rm /var/lib/xcp/networkd.db
systemctl start xcp-networkd
```
After the fix we get a working /etc/resolv.conf.
This affects master too.

CA-324959: do not loose DNS settings after a network reset

---

lib/network_utils.ml
test/network_test_lacp_properties.ml

This generates a config file of the form:
```
interface "xenbr0" {
send host-name = gethostname();
request subnet-mask, broadcast-address, time-offset, host-name, nis-domain, nis-servers, ntp-servers, interface-mtu, routers, domain-name, domain-name-servers;
}
```

Make dhclient send our hostname to the DHCP server

---

xapi-networkd.opam

Update the opam metadata to reflect dependencies, this frees the package from ounit, which doesn't use dune.

opam: tests depend on alcotest, not ounit

---

lib/network_utils.ml

xcp-networkd calls "dhclient -r" which releases the
current lease and stops the existing dhclient process. For some reason,
dhclient skips calling dhclient-script unless the lease file is given on
the command-line. This means that the dhclient hooks are not run which
in turn means that NTP servers obtained from DHCP are not removed.
Fix this by simply passing the lease file when stopping dhclient.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

CA-347400: Pass lease file when stopping dhclient

---

.ocamlformat
lib/network_utils.ml
networkd/network_server.ml

xcp-networkd fails to recognise the MAC address of an infiniband NIC
because it only looks for link/ether and misses link/infiniband. If the
former fails, look for link/infiniband, too.
This code could be made more general by using regular expressions for
search rather than strings. However, this would create more changes
which could complicate backports.
This is in response to https://github.com/xapi-project/xcp-networkd/issues/184
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

CA-351826 recognise link/infiniband MAC address

---

lib/network_utils.ml

The CA was triggered by a user with Infiniband devices that show up as network devices but are not supported. The original failure was that no mac address was found under `link/ether`. We now skip over devices that are not ethernet devices in the `list()` function that enumerates network interfaces. Backport of:
* 6db73c02 CA-351826 ensure PIF is an ethernet device                       
* 9ddfbf96 CA-351826 fail if we can't find MAC address of interface         
* 8678423d CA-351826 recognise link/infiniband MAC address

CA-351826 stockholm backport - ignore non-ethernet PIFs
