xapi-project/xcp-networkd

lib/network_utils.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> CA-184010: Add a timeout to script invocations

lib/network_utils.ml
Dhclient has a built-in timeout of its own, after which is backgrounds itself
and unblocks the caller.  We don't want dhclient to get killed by networkd
after some arbitrary timeout.
=> Don't use a timeout when executing dhclient

networkd/network_server.ml
This means that if we cannot setup one of the bridges, for some reason, we must
still try to configure the remaining ones.
=> CA-192116: On startup, each operation must be best effort

lib/network_utils.ml, networkd/network_server.ml
=> CA-203180: Linux bridge: disable IGMP snooping by default

networkd/network_server.ml
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
=> CP-15132: Legacy bringup script has moved out of init

networkd/network_server.ml
Reverts xapi-project/xcp-networkd#72
=> Revert "CP-15132: Legacy bringup script has moved out of init"

networkd/networkd.ml
=> CA-206909: Write PID file after finishing startup activities

lib/network_utils.ml, networkd/networkd.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> CA-209399: Set mac-table-size to 10000 when creating bridges

lib/network_utils.ml
=> CA-212083: In with_slaves_removed, call `f` if there are no slaves

.merlin, cli/network_cli.ml, lib/network_config.ml, lib/network_utils.ml, networkd/network_monitor.ml, networkd/network_monitor_thread.ml, networkd/network_server.ml, networkd/networkd.ml, networkd_db/networkd_db.ml, test/network_test_lacp_properties.ml
Do not merge yet. Here for review only.
=> Use packed stdext

lib/network_utils.ml
Signed-off-by: Liang Dai <liang.dai1@citrix.com>
=> CP-20569: Enable OVS IGMP Snooping by default

networkd/network_server.ml
xcp-networkd must stop and start the dhclient for the interface
if default gateway has changed.
Example:
1) If default gateway is xenbr0 - Its conf file will keep this
gateway information.
2) Switch the default gateway to xenbr1 - Its conf file will be
created with gateway information.
3) Switch the default gateway back to xenbr0 then dhclient won't
get restarted.
Reason:
1) While switching default gateway from xenbr0 to xenbr1,
gateway information from xenbr0 conf file was not removed.
2) On switching default gateway from xenbr1 to xenbr0, xcp-networkd
found no diff in conf file hence not retarted the dhclient for xenbr0.
It resulted default gateway still pointed to xenbr1.
Signed-off-by: sharad yadav <sharad.yadav@citrix.com>
=> CA-244087: Update dhclient interface conf on changing default gateway.

lib/network_utils.ml, networkd/network_server.ml, networkd/networkd.ml
Latest version according to internal review comments
=>  CP-23601 Inject IGMP snooping query message when IGMP snooping toggle

lib/network_utils.ml
Signed-off-by: Yarsin He <yarsin.he@citrix.com>
=> CA-264980: /usr/libexec/xenopsd/igmp_query_injector.py was broken

lib/network_utils.ml, networkd/network_server.ml, networkd/networkd.ml
=> REQ-230 merge feature branch to master

lib/network_utils.ml, networkd/network_server.ml, networkd/networkd.ml
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>
=> CP-25517: Extend get_capabilities interface to show SR-IOV capability

cli/jbuild, cli/network_cli.ml, lib/jbuild, lib/network_config.ml, lib/network_utils.ml, networkd/jbuild, networkd/network_monitor.ml, networkd/network_monitor_thread.ml, networkd/network_server.ml, networkd/networkd.ml, networkd_db/jbuild, profiling/jbuild, test/jbuild, test/network_test_lacp_properties.ml, test/test_jsonrpc_client.ml, xapi-networkd.opam
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
=> Port to `xapi-stdext-*` submodules and `Xstringext` -> `Astring`

lib/network_utils.ml
=> CA-276745: Fix Networkd.Sysfs.get_driver_name

networkd/network_server.ml
=> Add stub functions

networkd/network_server.ml
Implement interface to get pci bus path
=> CP-26333 Add PIF.pci field for network sriov feature

lib/network_utils.ml, networkd/network_server.ml, networkd/networkd.ml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/xapi-project/xcp-networkd/129)
=> CP-26856: unbind pciback driver before disable SR-IOV

networkd/network_server.ml, networkd/networkd.ml
This is for after rebase master then changes the interface to PPX.
=> Port sriov to ppx

lib/jbuild, lib/network_utils.ml, networkd/network_server.ml, networkd/networkd.ml
Merge feature SR-IOV to master
BST passed in job 81743
BVT passed in job 81742
=> Merge feature SR-IOV to master

lib/network_utils.ml
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
=> network_utils: reduce warnings

lib/jsonrpc_client.ml, lib/network_config.ml, lib/network_utils.ml, networkd/network_monitor.ml, networkd/network_monitor_thread.ml, networkd/network_server.ml, networkd/networkd.ml, networkd_db/networkd_db.ml, profiling/coverage.ml, profiling/coverage.mli, test/jsonrpc_dummy.ml, test/network_test.ml, test/network_test_lacp_properties.ml, test/test_jsonrpc_client.ml
Depends on xapi-project/xcp-idl#248.
=> Improve error handling

networkd/network_server.ml
=> Refine SR-IOV log

networkd/network_server.ml, networkd/networkd.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
=> New ocaml-rpc

lib/network_config.ml
Since we put in support for management-on-VLAN, setting up the management IP
address on first boot has been a little different.
In the past, xcp-networkd would set this up immediately by taking the
configuration from the MANAGEMENT_INTERFACE key in the inventory, and the
management.conf file in the first-boot data, both written by the host installer.
Then, we changed the host installer to no longer write the MANAGEMENT_INTERFACE
key, because we do not have a deterministic name for VLAN bridges: the
management bridge name becomes know only once the first-boot scripts run.
Besides, it is good to not have this naming policy encoded in the host
installer as well as in the Toolstack. The startup sequence of xcp-networkd was
changed to not configure anything in this case, and instead wait for …
=> CA-303529/CA-287657: Immediately setup management on first boot

lib/network_utils.ml, networkd/network_server.ml
=> Extend the naughty DHCP-server workaround to DNS

test/dune, test/network_test.ml, test/network_test_lacp_properties.ml, test/test_jsonrpc_client.ml
Signed-off-by: lippirk <ben.anson@citrix.com>
=> CP-28368 Propagate test_highlevel ounit removal

networkd/network_server.ml
=> Remove calls to obsolete network scripts

lib/network_utils.ml
... such as those pvsproxy ones which have type=internal.
Signed-off-by: Zheng Li <zheng.li3@citrix.com>
=> CA-323765: preserve the "type" config when re-adding existing interfaces

lib/network_config.ml
Same as https://github.com/xapi-project/xcp-networkd/pull/168 but for master
=> CA-324959: do not loose DNS settings after a network reset

lib/network_utils.ml
Signed-off-by: lippirk <ben.anson@citrix.com>
=> CP-32106: backport of CA-323765

networkd/network_monitor_thread.ml
It the 'ip monitor address' process quitted for some reason, xcp-networkd
will be logging in an infinite loop and soon eat up the /var/log space.
=> Restart 'ip monitor address' process if it quitted

lib/network_utils.ml
=> CA-329442: Avoid recreating bridges unless absolutely necessary

.travis.yml
Travis is currently failing, lets use the updated configuration
=> Use common Travis CI configuration

.ocamlformat, Makefile, dune-project, lib/jsonrpc_client.ml, lib/jsonrpc_client.mli, lib/network_config.ml, lib/network_utils.ml, networkd/network_monitor.ml, networkd/network_monitor_thread.ml, networkd/network_server.ml, networkd/networkd.ml, networkd_db/networkd_db.ml, profiling/coverage.ml, profiling/coverage.mli, test/jsonrpc_dummy.ml, test/network_test.ml, test/network_test_lacp_properties.ml, test/test_jsonrpc_client.ml
This is using the same configuration as https://github.com/xapi-project/xcp-idl/pull/310
=> Format ocaml code using ocamlformat

networkd/dune, networkd/network_server.ml, test/test_jsonrpc_client.ml, xapi-networkd.opam
Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>
=> CP-33121: remove stdext's monadic usage

networkd/network_server.ml
Depends on https://github.com/xapi-project/xs-opam/pull/511
=> CP-34942: update for rpclib 8 compatibility
